[gateway]
host = 127.0.0.1
port = 7000
password = your_password
tgw_id = W123456Y0001
# required_platforms用于平台会话连接的告警，值为需要告警的平台ID，逗号分隔，默认1-6
# 告警规则：需要告警的平台ID + tgw的config.xml平台已配置 + 会话未连接：
# tgw的config.xml未配置平台，在required_platforms中包含该平台时，不会对平台会话的未连接状态进行告警
# tgw的config.xml配置了平台，在required_platforms中未包含该平台时，不会对平台会话的未连接状态进行告警
# 1-集中竞价交易平台 2-综合金融服务平台 3-非交易处理平台
# 4-衍生品平台 5-国际市场互联平台 6-固定收益平台
required_platforms = 1,2,3,4,5,6

[collector]
interval = 1
# 静态状态刷新间隔，单位秒，默认300秒（5分钟），设为0则不启用定期刷新
static_status_interval = 300
# 心跳间隔，单位秒，默认20秒，不能超过30秒
heartbeat_interval = 20
timeout = 5.0
retry_interval = 5

[telegraf]
debug = true