{
 "title": "tgw_monitor_v0.1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "tgw_id", "label": "tgw网关号", "query": { "query": "label_values(tgw_up,tgw_id)" } }
  ]
 },
 "panels": [
  { "title": "tgw总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "tgw监控总览",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "targets": [
    { "expr": "tgw_up{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "tgw信息总览（需连上监控端口）",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "targets": [
    { "expr": "tgw_up{}", "legendFormat": "__auto" },
    {
     "expr": "tgw_certificationExpireTime - time()",
     "legendFormat": "__auto"
    },
    { "expr": "tgw_RunStatus_commStatus{} - 0", "legendFormat": "__auto" },
    {
     "expr": "tgw_latestGatewayVersion{} == bool tgw_progVersion{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "6 - count by(tgw_id) (tgw_RunStatus_platformState{} == -99)",
     "legendFormat": "__auto"
    },
    {
     "expr": "6 - count by(tgw_id) (tgw_SessionStatus_sessionStatus{} == -99) ",
     "legendFormat": "__auto"
    },
    { "expr": "tgw_RunStatus_envId{}", "legendFormat": "__auto" },
    { "expr": "tgw_RunStatus_orderRate{}", "legendFormat": "__auto" },
    {
     "expr": "(\r\n  count(tgw_RunStatus_platformState{} != 99 and tgw_RunStatus_platformState{} != -99) by (tgw_id) \r\n  == bool \r\n  (6 - count(tgw_SessionStatus_sessionStatus{} == -99) by (tgw_id))\r\n)\r\n+\r\n(\r\n (6 - count(tgw_SessionStatus_sessionStatus{} == -99) by (tgw_id))\r\n  == bool \r\n  count(tgw_required_platforms{} == 1) by (tgw_id)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$tgw_id 详细信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "tgw_id" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_up{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "{{tgw_host}}:{{tgw_monitor_port}}"
    }
   ]
  },
  {
   "title": "网关类型",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_gatewayType{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "操作系统{{osType}}"
    }
   ]
  },
  {
   "title": "版本",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_progVersion{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "运行版本"
    },
    {
     "expr": "tgw_latestGatewayVersion{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "最新版本"
    }
   ]
  },
  {
   "title": "数量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_RunStatus_orderCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "已发委托数"
    },
    {
     "expr": "tgw_RunStatus_orderConfirmCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "收到委托确认数"
    },
    {
     "expr": "tgw_RunStatus_reportCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "收到成交回报数"
    }
   ]
  },
  {
   "title": "各平台状态",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "tgw_RunStatus_platformState{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  tgw_SessionStatus_sessionStatus{tgw_id=\"${tgw_id}\"} == 1 and on(platform_id) tgw_RunStatus_platformState{tgw_id=\"${tgw_id}\"} != -99,\r\n  \"status\", \"normal\", \"\", \"\"\r\n)\r\nor\r\nlabel_replace(\r\n  tgw_SessionStatus_sessionStatus{tgw_id=\"${tgw_id}\"} == 2 and on(platform_id) tgw_RunStatus_platformState{tgw_id=\"${tgw_id}\"} != -99,\r\n  \"status\", \"abnormal\", \"\", \"\"\r\n)\r\nor\r\nlabel_replace(\r\n  tgw_SessionStatus_sessionStatus{tgw_id=\"${tgw_id}\"} == -99 and on(platform_id) tgw_RunStatus_platformState{tgw_id=\"${tgw_id}\"} != -99,\r\n  \"status\", \"unestablished\", \"\", \"\"\r\n) \r\nor \r\nlabel_replace(\r\n  tgw_SessionStatus_sessionStatus{tgw_id=\"${tgw_id}\"} == -99 and on(platform_id) tgw_RunStatus_platformState{tgw_id=\"${tgw_id}\"} == -99,\r\n  \"status\", \"unconfigured\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "tgw_SessionStatus_orderCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "tgw_SessionStatus_orderConfirmCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "tgw_SessionStatus_reportCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "tgw_SessionStatus_invalidOrderCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "tgw_SessionStatus_businessRejectCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "交易所通信",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_RunStatus_commStatus{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "{{serverAddress}}"
    }
   ]
  },
  {
   "title": "证书剩余时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_certificationExpireTime{tgw_id=\"${tgw_id}\"} - time()",
     "legendFormat": "证书剩余时间"
    },
    {
     "expr": "tgw_certificationExpireTime{tgw_id=\"${tgw_id}\"} * 1000",
     "legendFormat": "证书有效期"
    }
   ]
  },
  {
   "title": "异常单",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_RunStatus_invalidOrderCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "非法委托数"
    },
    {
     "expr": "tgw_RunStatus_businessRejectCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "业务拒绝消息数"
    }
   ]
  },
  {
   "title": "速率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_RunStatus_orderRate{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "速率限制"
    },
    {
     "expr": "tgw_RunStatus_orderRate{tgw_id=\"${tgw_id}\"}/50",
     "legendFormat": "流速权"
    }
   ]
  },
  {
   "title": "环境号",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_RunStatus_envId{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "环境号"
    }
   ]
  },
  {
   "title": "委托确认差值",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_RunStatus_orderCount{tgw_id=\"${tgw_id}\"} - tgw_RunStatus_orderConfirmCount{tgw_id=\"${tgw_id}\"} - tgw_RunStatus_invalidOrderCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "委托确认差值"
    }
   ]
  },
  {
   "title": "模式",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgw_RunStatus_testMode{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "模式"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "tgw_RunStatus_orderCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "已发委托数"
    },
    {
     "expr": "tgw_RunStatus_orderConfirmCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "收到委托确认数"
    },
    {
     "expr": "tgw_RunStatus_reportCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "收到成交回报数"
    },
    {
     "expr": "tgw_RunStatus_invalidOrderCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "非法委托数"
    },
    {
     "expr": "tgw_RunStatus_businessRejectCount{tgw_id=\"${tgw_id}\"}",
     "legendFormat": "业务拒绝消息数"
    }
   ]
  }
 ]
}